<robot name="mycar" xmlns:xacro="http://www.ros.org/wiki/xacro">
 
    <xacro:property name="PI" value="3.141"/>
 
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
 
    <xacro:property name="footprint_radius" value="0.001" /> 
    <xacro:property name="base_radius" value="0.1" /> 
    <xacro:property name="base_length" value="0.08" /> 
    <xacro:property name="earth_space" value="0.015" /> 
     <xacro:property name="base_joint_z" value="${base_length / 2 + earth_space}" /> 
 
     <xacro:property name="base_mass" value="2" /> 
 
    <!-- base -->
    <link name="base_footprint">
      <visual>
        <geometry>
          <sphere radius="${footprint_radius}" />
        </geometry>
      </visual>
    </link>
 
    <link name="base_link">
      <visual>
        <geometry>
          <cylinder radius="${base_radius}" length="${base_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="baselink_color">
          <color rgba="1.0 0.5 0.2 0.7" />
        </material>
      </visual>
 
      <collision>
        <geometry>
          <cylinder radius="${base_radius}" length="${base_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <xacro:cylinder_inertial_matrix m="${base_mass}" r="${base_radius}" h="${base_length}" />
 
    </link>
 
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>
 
    <joint name="link2footprint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 ${earth_space + base_length / 2 }"  rpy="0 0 0"/>
    </joint>
 
    <!-- qudong wheel -->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="wheel_mass" value="0.05" />
    
    <xacro:macro name="add_wheels" params="name flag">
      <link name="${name}_wheel">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
          <material name="black" />
        </visual>
 
        <collision>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
 
      </link>
 
      <gazebo reference="${name}_wheel">
        <material>Gazebo/Red</material>
      </gazebo>
 
      <joint name="${name}_wheel2base_link" type="continuous">
        <parent link="base_link" />
        <child link="${name}_wheel" />
        <origin xyz="0 ${flag * base_radius} ${-(earth_space + base_length / 2 - wheel_radius) }" />
        <axis xyz="0 1 0" />
      </joint>
    </xacro:macro>
    <xacro:add_wheels name="left" flag="1" />
    <xacro:add_wheels name="right" flag="-1" />
 
    <!-- zhicheng/wanxiang wheel -->
    <xacro:property name="support_wheel_radius" value="0.0075" /> 
    <xacro:property name="support_wheel_mass" value="0.01" /> 
 
    <xacro:macro name="add_support_wheel" params="name flag" >
      <link name="${name}_wheel">
        <visual>
            <geometry>
                <sphere radius="${support_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="black" />
        </visual>
 
        <collision>
            <geometry>
                <sphere radius="${support_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertial_matrix m="${support_wheel_mass}" r="${support_wheel_radius}" />
 
      </link>
 
      <gazebo reference="${name}_wheel">
        <material>Gazebo/Red</material>
      </gazebo>
 
      <joint name="${name}_wheel2base_link" type="continuous">
          <parent link="base_link" />
          <child link="${name}_wheel" />
          <origin xyz="${flag * (base_radius - support_wheel_radius)} 0 ${-(base_length / 2 + earth_space / 2)}" />
          <axis xyz="1 1 1" />
      </joint>
    </xacro:macro>
 
    <xacro:add_support_wheel name="front" flag="1" />
    <xacro:add_support_wheel name="back" flag="-1" />
 
</robot>
